const fs = require('fs');
const path = require('path');

// Site categories
const SITE_CATEGORIES = [
  'ammunition',
  'gear',
  'gun-parts',
  'magazines',
  'optics',
  'outdoors',
  'reloading',
  'sale'
];

// Chattanooga categories from the analysis
const CHATTANOOGA_CATEGORIES = [
  "3D Targets",
  "Accessories",
  "Accessories|Hunting",
  "Accessory Holsters",
  "Accessory Holsters|Holster Accessories",
  "Action Cameras",
  "Action Cameras|Archery Accessories",
  "Adapters & Rails",
  "Air Gun Accessories",
  "Air Gun Accessories|Airgun Accessories",
  "Air Gun Accessories|Airgun Handguns",
  "Air Gun Accessories|Airgun Rifles",
  "Air Gun Accessories|Pellets & BBs",
  "Air Gun Pellets & BBs",
  "Air Gun Pellets & BBs|Airgun Accessories",
  "Air Gun Pellets & BBs|Pellets & BBs",
  "Air Pistols",
  "Air Pistols|Airgun Accessories",
  "Air Pistols|Airgun Handguns",
  "Air Rifle Scopes",
  "Air Rifles",
  "Air Rifles|Airgun Accessories",
  "Air Rifles|Airgun Handguns",
  "Air Rifles|Airgun Rifles",
  "Airgun Rifles",
  "Airguns|Air Gun Accessories",
  "Airguns|Air Gun Accessories|Airgun Accessories",
  "Airguns|Air Gun Pellets & BBs|Pellets & BBs",
  "Airguns|Air Rifles",
  "Airguns|Air Rifles|Airgun Rifles",
  "Airguns|Airsoft Guns|Airgun Handguns",
  "Airsoft Guns|Airgun Handguns",
  "Airsoft Guns|Airgun Rifles",
  "Alignment Leveling & Other Tools",
  "Alignment Leveling & Other Tools|Punches",
  "Alignment Leveling & Other Tools|Scope/Sight Mounting",
  "Alignment Leveling & Other Tools|Screwdrivers & Torque Wrenches",
  "Alignment Leveling & Other Tools|Tools",
  "Ammo & Bullet Storage",
  "Ammo Boxes",
  "Ammo Boxes|Ammo Cans & Dry Box",
  "Ammo Cans & Dry Box",
  "Ammo Cans & Dry Box|Packs & Bags",
  "Ammunition|Handgun Ammunition",
  "Ammunition|Rifle Ammunition",
  "Ammunition|Rimfire Ammunition",
  "Ammunition|Shotgun Ammunition",
  "Archery Accessories",
  "Archery Accessories|3D Targets",
  "Archery Accessories|Archery Sights|Archery Scopes",
  "Archery Accessories|Arrow Rests",
  "Archery Accessories|Block & Foam Targets",
  "Archery Accessories|Bow Cases",
  "Archery Accessories|Bow Scales",
  "Archery Accessories|Bowfishing Accessories",
  "Archery Accessories|Chronographs & Shot Timers",
  "Archery Accessories|Crossbow Accessories",
  "Archery Accessories|Crossbow Targets",
  "Archery Accessories|Leveling & Alignment Tools",
  "Archery Accessories|Mathews Bridge-Lock Sights & Accessories",
  "Archery Accessories|Multi-Tools & Tool Kits",
  "Archery Accessories|Oil & Lubricants",
  "Archery Accessories|Peep Sights",
  "Archery Accessories|Rangefinders",
  "Archery Accessories|Sights & Scopes",
  "Archery Accessories|Stabilizers & Dampers",
  "Archery Scopes|Centerfire Scopes",
  "Archery Sights|Archery Scopes",
  "Archery Sights|Archery Scopes|Rangefinders",
  "Arrow Building & Repair",
  "Arrow Building & Repair|Archery Accessories",
  "Arrow Components",
  "Arrow Components|Archery Accessories",
  "Arrow Rests",
  "Arrow Tubes & Cases",
  "Arrows",
  "Arrows|Archery",
  "Axes Hatchets & Machetes",
  "Backpacking",
  "Backpacks",
  "Backpacks|Handgun Cases",
  "Backpacks|Handgun Cases|Packs & Bags",
  "Backpacks|Packs & Bags",
  "Bag Targets",
  "Bags & Duffels",
  "Bags & Packs",
  "Bags & Packs|Ammo Cans & Dry Box",
  "Bags & Packs|Binocular Cases & Harnesses",
  "Bags & Packs|Clay Target Throwers",
  "Bags & Packs|Packs & Bags",
  "Bags & Packs|Pouches",
  "Bags & Packs|Range Bags",
  "Barrels",
  "Barrels|Caliber Conversions",
  "Barrels|Chassis & Stocks",
  "Barrels|Parts/Parts Kits",
  "Bases & Mounts by Gun Make & Model",
  "Batteries",
  "Batteries|Flashlights & Accessories",
  "Bear Safety Gear",
  "Bear Safety Gear|Pepper Spray",
  "Bear Safety Gear|Self Defense Accessories",
  "Beds & Pads",
  "Beds & Pads|Beds",
  "Belts",
  "Belts|Gun Holsters",
  "Belts|Holster & Duty Belts",
  "Belts|Holster Accessories",
  "Belts|Shooting|Holster & Duty Belts",
  "Benches & Stands",
  "Bibs & Coveralls",
  "Big Game Decoys",
  "Binocular Cases & Harnesses",
  "Binocular Cases & Harnesses|Pouches",
  "Binoculars",
  "Binoculars|Binocular Cases & Harnesses",
  "Binoculars|Binoculars",
  "Binoculars|Binoculars & Monoculars",
  "Binoculars|Night Vision Binoculars",
  "Binoculars|Optics|Binoculars",
  "Binoculars|Rangefinding Binoculars",
  "Bipods",
  "Black Powder Cannons",
  "Black Powder Pistol Kits",
  "Black Powder Pistols",
  "Black Powder Rifle Kits",
  "Black Powder Rifles",
  "Black Powder Substitutes",
  "Black Powder Substitutes & Accessories",
  "Black Powder Substitutes & Accessories|Black Powder Substitutes",
  "Black Powder Substitutes|Muzzleloader Cappers & Speed Loaders",
  "Blind Accessories",
  "Blind Accessories|Archery Accessories",
  "Blind Accessories|Shooting Rests",
  "Blind Bags",
  "Blind Bags|Hunting Packs",
  "Blind Chairs",
  "Blind Chairs|Chairs",
  "Blind Chairs|Shooting",
  "Blind Chairs|Treestand Accessories",
  "Blind Chairs|Waterfowl Blinds",
  "Block & Foam Targets",
  "Bolt Carriers",
  "Bolt Carriers|Lowers",
  "Bolts",
  "Boots & Shoes",
  "Boots & Shoes|Boots & Shoes",
  "Boots & Shoes|Boots & Shoes|Clothing & Footwear",
  "Boots & Shoes|Clothing & Footwear",
  "Boresighters",
  "Boresighters|Scope/Sight Mounting",
  "Bow Cases",
  "Bow Cases|Archery|Handgun Cases",
  "Bow Cases|Cases Safes & Storage",
  "Bow Cases|Rifle Cases",
  "Bow Cases|Slings",
  "Bowfishing",
  "Bowfishing Accessories",
  "Bowls & Feeders|Medical",
  "Box Calls",
  "Box Calls|Mouth Calls|Slate & Glass Calls",
  "Box Calls|Slate & Glass Calls",
  "Brass",
  "Brass Catchers",
  "Brass Catchers|Pouches",
  "Breech & Wrenches",
  "Broadheads Field & Specialty Points",
  "Broadheads Field & Specialty Points|Archery Accessories",
  "Buffer Tubes/Buffers & Springs",
  "Buffer Tubes/Buffers & Springs|Parts/Parts Kits",
  "Bullet Casting",
  "Bullet Casting|Dies",
  "Bullet Pullers",
  "CA Compliant",
  "CSSI Exclusive Shop",
  "CSSI Exclusive Shop|Centerfire Scopes",
  "CSSI Exclusive Shop|Grips",
  "CSSI Exclusive Shop|Handgun Ammunition",
  "CSSI Exclusive Shop|Single Stage Presses",
  "Caliber Conversions",
  "Calipers & Micrometers",
  "Camp Tools",
  "Campground",
  "Caps Hats & Beanies",
  "Caps Hats & Beanies|Caps Hats & Beanies",
  "Caps Hats & Beanies|Caps Hats & Beanies|Hats",
  "Caps Hats & Beanies|Clothing & Footwear",
  "Caps Hats & Beanies|Hats",
  "Caps Hats & Beanies|Hats|Clothing & Footwear",
  "Cartridge Holders",
  "Case Lubes",
  "Case Prep Tools",
  "Cases Safes & Storage|Ammo Boxes",
  "Cases Safes & Storage|Gun Locks",
  "Cases Safes & Storage|Gun Safes & Cabinets",
  "Cases Safes & Storage|Handgun Cases",
  "Cases Safes & Storage|Handgun Cases|Pouches",
  "Cases Safes & Storage|Handgun Cases|Storage & Organization Accessories",
  "Cases Safes & Storage|Rifle Cases",
  "Cases Safes & Storage|Shooting Rests",
  "Cases Safes & Storage|Storage & Organization Accessories",
  "Cellular Trail Cameras",
  "Cellular Trail Cameras|Hunting",
  "Centerfire Scopes",
  "Chairs",
  "Charging Handles/Bolt Knobs",
  "Chassis & Stocks",
  "Chassis & Stocks|Chassis & Stocks",
  "Chokes/Muzzle Devices",
  "Chokes/Muzzle Devices|Screwdrivers & Torque Wrenches",
  "Chronographs & Shot Timers",
  "Clay Target Throwers",
  "Cleaning Brushes Mops and Swabs",
  "Cleaning Brushes Mops and Swabs|Breech & Wrenches",
  "Cleaning Brushes Mops and Swabs|Muzzleloader Cleaning & Accessories",
  "Cleaning Mats",
  "Cleaning Mats|Gun Cleaning Mats",
  "Climbing Sticks",
  "Climbing Treestands",
  "Cloths & Wipes",
  "Collars & Leashes",
  "Collars & Leashes|Collars Leashes & Harnesses",
  "Compasses|Emergency & Survival",
  "Components",
  "Components|Brass",
  "Compound Bows",
  "Cookware",
  "Crossbow Accessories",
  "Crossbow Targets",
  "Crossbows",
  "Crossbows|Archery",
  "Decoy Accessories",
  "Decoy Bags",
  "Decoy Bags|Dry Bags|Bags & Duffels",
  "Deer Calls",
  "Die Parts Shell Holders & Accessories",
  "Die Parts Shell Holders & Accessories|Powder Measures Dispensers & Scales",
  "Die Parts Shell Holders & Accessories|Shell Holders & Plates",
  "Dies",
  "Dies|Benches & Stands",
  "Dies|Calipers & Micrometers",
  "Dies|Case Lubes",
  "Dies|Case Prep Tools",
  "Dies|Powder Measures Dispensers & Scales",
  "Dies|Replacement Parts",
  "Displays",
  "Dog Blinds",
  "Dog Blinds|Beds",
  "Dog Blinds|Beds|Hunting",
  "Dog Blinds|Hunting",
  "Dog Training",
  "Dog Training|Collars Leashes & Harnesses",
  "Dog Training|Toys",
  "Dog Training|Training",
  "Dove Decoys",
  "Dry Bags",
  "Dry Bags|Bags & Duffels",
  "Dry Bags|Bags & Duffels|Ammo Boxes",
  "Dry Bags|Bags & Duffels|Range Bags",
  "Dry Bags|Bags & Duffels|Range Bags|Handgun Cases",
  "Dry Bags|Bags & Duffels|Range Bags|Shooting Rests",
  "Duck Calls",
  "Duck Calls|Hunting",
  "Duck Decoys",
  "Duck Decoys|Hunting",
  "Dummy Rounds",
  "Dummy Rounds|Snap Caps & Dummy Rounds|Cleaning Brushes Mops and Swabs|Snap Caps & Dummy Rounds",
  "Dummy Rounds|Snap Caps & Dummy Rounds|Snap Caps & Dummy Rounds",
  "Ear & Eye Combo Kits",
  "Ear Muffs",
  "Ear Plugs",
  "Electronic Calls",
  "Electronic Collars|Collars Leashes & Harnesses",
  "Electronic Game Calls",
  "Electronic Game Calls|Predator Calls",
  "Elk Calls",
  "Elk Calls|Hunting",
  "Emergency & Survival",
  "Facemasks Balaclavas & Neck Gaiters",
  "Feeders",
  "Feeders|Hunting",
  "Feeders|Lanterns",
  "Fiber Optic Sights",
  "Field Products",
  "Firearms|Grips",
  "Firepits & Heating",
  "First Aid",
  "First Aid Kits|First Aid Kits",
  "First Aid|First Aid Kits",
  "First Aid|First Aid Kits|First Aid Kits",
  "First Aid|Shooting",
  "Flashlights",
  "Flashlights & Accessories",
  "Flashlights & Accessories|Accessory Holsters",
  "Flashlights|Flashlights & Accessories",
  "Flashlights|Optics|Flashlights & Accessories",
  "Flintlock",
  "Food",
  "Food Dehydrators",
  "Food Plots",
  "Game Processing",
  "Gas Blocks/Gas Tubes",
  "Gloves",
  "Gloves|Facemasks Balaclavas & Neck Gaiters",
  "Gloves|Gloves",
  "Gloves|Gloves|Gloves",
  "Gloves|Vests",
  "Goose Calls",
  "Goose Calls|Hunting",
  "Goose Decoys",
  "Grips",
  "Ground Blinds",
  "Ground Blinds|Hunting",
  "Gun & Magazine Combo Holsters",
  "Gun Bluing",
  "Gun Bluing|Gun Cleaning Kits",
  "Gun Bore Guides",
  "Gun Cleaning Accessories",
  "Gun Cleaning Jags Patch Holders & Patches",
  "Gun Cleaning Jags Patch Holders & Patches|Muzzleloader Cleaning & Accessories",
  "Gun Cleaning Kits",
  "Gun Cleaning Kits|Air Gun Accessories",
  "Gun Cleaning Kits|Muzzleloader Cleaning & Accessories",
  "Gun Cleaning Mats",
  "Gun Cleaning Rods",
  "Gun Cleaning Rods|Muzzleloader Ramrods",
  "Gun Cleaning Tools",
  "Gun Cleaning Tools|Muzzleloader Cleaning & Accessories",
  "Gun Holsters",
  "Gun Holsters|Holster Accessories",
  "Gun Locks",
  "Gun Oils & Gun Cleaning Solvents",
  "Gun Oils & Gun Cleaning Solvents|Muzzleloader Cleaning & Accessories",
  "Gun Parts & Tools",
  "Gun Parts & Tools|Handguards",
  "Gun Parts & Tools|Scope Bases & Mounts",
  "Gun Parts & Tools|Triggers",
  "Gun Parts|Barrels",
  "Gun Parts|Bolt Carriers",
  "Gun Parts|Caliber Conversions",
  "Gun Parts|Chassis & Stocks",
  "Gun Parts|Chokes/Muzzle Devices",
  "Gun Parts|Dummy Rounds|Snap Caps & Dummy Rounds|Snap Caps & Dummy Rounds",
  "Gun Parts|Grips",
  "Gun Parts|Handguards",
  "Gun Parts|Handgun Magazines",
  "Gun Parts|Lowers|Grips",
  "Gun Parts|Magazine Accessories",
  "Gun Parts|Magazine Releases",
  "Gun Parts|Muzzle Devices",
  "Gun Parts|Night Sights",
  "Gun Parts|Parts",
  "Gun Parts|Recoil Pads",
  "Gun Parts|Rifle Magazines",
  "Gun Parts|Shotgun Lights",
  "Gun Parts|Triggers",
  "Gun Parts|Uppers",
  "Gun Safes & Cabinets",
  "Gun Vises",
  "Gun Vises|Gun Cleaning Kits",
  "Gun Vises|Gun Cleaning Tools",
  "Gun Vises|Vices & Cradles",
  "Hammocks",
  "Handcuffs & Restraints",
  "Handguards",
  "Handgun Ammunition",
  "Handgun Ammunition|Rifle Ammunition",
  "Handgun Cases",
  "Handgun Cases|Pouches",
  "Handgun Lights",
  "Handgun Lights|Rifle Lights",
  "Handgun Magazines",
  "Handgun Magazines|Rifle Magazines",
  "Handgun Sights",
  "Handguns",
  "Handguns|CA Compliant",
  "Handguns|CA Compliant|CSSI Exclusive Shop",
  "Handguns|CA Compliant|Firearms",
  "Handguns|CA Compliant|MA Compliant",
  "Handguns|CSSI Exclusive Shop",
  "Handguns|CSSI Exclusive Shop|Firearms",
  "Handguns|Firearms",
  "Handguns|MA Compliant",
  "Handguns|Used Guns",
  "Handguns|Used Guns|CA Compliant",
  "Handguns|Used Guns|CSSI Exclusive Shop",
  "Hang On Treestands",
  "Hats",
  "Headlamps",
  "Headlamps|Flashlights & Accessories",
  "Headlamps|Knives|Knives",
  "Headlamps|Optics",
  "Headspace Gauges",
  "Headspace Gauges|Calipers & Micrometers",
  "Headspace Gauges|Powder Measures Dispensers & Scales",
  "Health & Safety",
  "Holster & Duty Belts",
  "Holster Accessories",
  "Hoodies & Sweatshirts",
  "Hoodies & Sweatshirts|Clothing & Footwear",
  "Hoodies & Sweatshirts|Hoodies & Sweatshirts",
  "Hoodies & Sweatshirts|Long Sleeve Shirts",
  "Hunting",
  "Hunting Accessories",
  "Hunting Eyewear|Safety Glasses|Shooting Glasses",
  "Hunting Eyewear|Shooting Glasses",
  "Hunting Eyewear|Sunglasses|Shooting Glasses",
  "Hunting Eyewear|Sunglasses|Sunglasses",
  "Hunting Eyewear|Sunglasses|Sunglasses|Shooting Glasses",
  "Hunting Packs",
  "Hunting Pants",
  "Hunting Safety",
  "Hunting Safety|Shooting Vests",
  "Hunting Vests",
  "Hunting|Electronic Game Calls",
  "Hygiene Products",
  "Inline",
  "Insect Repellants",
  "Jackets Coats & Parkas",
  "Jackets Coats & Parkas|Jackets Coats & Parkas",
  "Knives",
  "Knives & Edged Tools",
  "Knives & Edged Tools|Axes Hatchets & Machetes",
  "Knives & Edged Tools|Axes Hatchets & Machetes|Knives",
  "Knives & Edged Tools|Axes Hatchets & Machetes|Knives & Edged Tools",
  "Knives & Edged Tools|Emergency & Survival",
  "Knives & Edged Tools|Knives",
  "Knives & Edged Tools|Knives & Edged Tools",
  "Knives & Edged Tools|Knives|Knives",
  "Knives & Edged Tools|Knives|Knives & Edged Tools",
  "Knives & Edged Tools|Multi-Tools",
  "Knives & Edged Tools|Multi-Tools|Emergency & Survival",
  "Knives & Edged Tools|Multi-Tools|Knives & Edged Tools",
  "Knives & Edged Tools|Pouches",
  "Knives|Axes Hatchets & Machetes|Knives",
  "Knives|Knives",
  "Knives|Knives & Edged Tools",
  "Knives|Knives & Edged Tools|Knives",
  "Knives|Multi-Tools|Knives",
  "Knives|Self Defense Accessories|Knives",
  "Ladder Treestands",
  "Lanterns",
  "Lanterns|Batteries",
  "Lanyards",
  "Lanyards|Training",
  "Laser Sights",
  "Laundry Detergent",
  "Locator Calls",
  "Long Sleeve Shirts",
  "Long Sleeve Shirts|Clothing & Footwear",
  "Long Sleeve Shirts|Hoodies & Sweatshirts",
  "Long Sleeve Shirts|Long Sleeve Shirts",
  "Lowers",
  "Lowers|Grips",
  "Lowers|Lowers",
  "Lowers|Uppers",
  "MA Compliant",
  "Magazine Accessories",
  "Magazine Accessories|Packs & Bags",
  "Magazine Accessories|Slings & Swivels",
  "Magazine Catches",
  "Magazine Catches|Magazine Catches",
  "Magazine Extensions",
  "Magazine Extensions|Parts",
  "Magazine Holsters",
  "Magazine Pouches",
  "Magazine Releases",
  "Magazine Releases|Parts",
  "Magazine Speedloaders",
  "Magazine Speedloaders|Speedloaders & Accessories",
  "Magazine Speedloaders|Speedloaders & Accessories|Pouches",
  "Magazine Storage",
  "Magazine Tubes",
  "Magnifier",
  "Manuals",
  "Mathews Bridge-Lock Sights & Accessories",
  "Meat Grinders",
  "Meat Mixers",
  "Meat Saws",
  "Meat Saws|Hunting",
  "Meat Slicers",
  "Minerals & Attractants",
  "Monoculars",
  "Monopods",
  "Monopods|Shooting Sticks",
  "Mouth Calls",
  "Multi-Tools",
  "Multi-Tools & Tool Kits",
  "Muzzle Devices",
  "Muzzle Devices|Tools",
  "Muzzleloader Bullets & Sabots",
  "Muzzleloader Bullets & Sabots|Muzzleloader Bullets & Sabots",
  "Muzzleloader Cappers & Speed Loaders",
  "Muzzleloader Cleaning & Accessories",
  "Muzzleloader Ramrods",
  "Muzzleloader Scopes",
  "Muzzleloaders",
  "Night Sights",
  "Night Vision Accessories",
  "Night Vision Binoculars",
  "Night Vision Binoculars|Thermal Binoculars",
  "Night Vision Goggles",
  "Night Vision Monoculars",
  "Night Vision Rifle Scopes",
  "Night Vision Rifle Scopes|Thermal Rifle Scopes",
  "Night Vision|Thermal Rifle Scopes",
  "Non Cellular Trail Cameras",
  "Non Cellular Trail Cameras|Navigation & Observation",
  "Oil & Lubricants",
  "Optics",
  "Optics|Bases & Mounts by Gun Make & Model",
  "Optics|Binocular Cases & Harnesses",
  "Optics|Binoculars",
  "Optics|Centerfire Scopes",
  "Optics|Chassis & Stocks",
  "Optics|Handgun Lights",
  "Optics|Laser Sights",
  "Optics|Night Sights",
  "Optics|Night Vision Goggles",
  "Optics|Night Vision Monoculars",
  "Optics|Rangefinding Binoculars|Rangefinders|Rangefinding Binoculars",
  "Optics|Red Dot Sight Mounts & Adapters",
  "Optics|Reflex",
  "Optics|Rifle Lights",
  "Optics|Scope Bases & Mounts",
  "Optics|Scope Covers & Sunshades",
  "Optics|Scope Rings",
  "Optics|Spotting Scopes",
  "Optics|Thermal Accessories",
  "Optics|Thermal Imaging Cameras",
  "Optics|Thermal Monoculars",
  "Optics|Thermal Rifle Scopes",
  "Optics|Tube",
  "Outdoors",
  "Outdoors|Backpacks",
  "Outdoors|Flashlights",
  "PFDs",
  "Packs & Bags",
  "Packs & Bags|Gun Holsters",
  "Packs & Bags|Holster Accessories",
  "Paint Stain Polish & Finish",
  "Paint Stain Polish & Finish|Cloths & Wipes",
  "Paint Stain Polish & Finish|Gun Cleaning Kits",
  "Pants",
  "Pants|Clothing & Footwear",
  "Pants|Hunting Pants",
  "Paper Targets",
  "Parts",
  "Parts/Parts Kits",
  "Parts/Parts Kits|Ammo Boxes",
  "Parts/Parts Kits|Slings & Swivels",
  "Parts|Cartridge Holders",
  "Pellets & BBs",
  "Pepper Gun Accessories",
  "Pepper Guns",
  "Pepper Spray",
  "Pepper Spray|Pepper Gun Accessories",
  "Percussion Cap",
  "Percussion Caps & Primers",
  "Personal Defense & Security",
  "Personal Defense & Security|Emergency & Survival|Self Defense Accessories",
  "Personal Defense & Security|Handcuffs & Restraints",
  "Personal Defense & Security|Knives|Handcuffs & Restraints",
  "Personal Defense & Security|Knives|Self Defense Accessories",
  "Personal Defense & Security|Pepper Gun Accessories",
  "Personal Defense & Security|Pepper Guns",
  "Personal Defense & Security|Pepper Spray",
  "Personal Defense & Security|Plate Carriers|Plate Carriers & Chest Rigs",
  "Personal Defense & Security|Self Defense Accessories",
  "Personal Defense & Security|Shooting Vests|Plate Carriers & Chest Rigs",
  "Personal Defense & Security|Stun Guns",
  "Personal Defense & Security|Stun Guns|Flashlights & Accessories",
  "Personal Defense & Security|TASER Accessories",
  "Personal Defense & Security|TASER Devices",
  "Personal Defense & Security|TASER Devices|Flashlights & Accessories",
  "Picatinny-Style Universal Mounts",
  "Picatinny-Style Universal Mounts|Handguards",
  "Picatinny-Style Universal Mounts|Parts/Parts Kits",
  "Picatinny-Style Universal Mounts|Scope Rings",
  "Pistol Brass",
  "Pistol Bullets",
  "Pistol Bullets|Muzzleloader Bullets & Sabots",
  "Pistol Dies",
  "Pistol Powder",
  "Pistol Primers",
  "Pistol Scopes",
  "Plate Carriers",
  "Plate Carriers|Plate Carriers & Chest Rigs",
  "Portable Showers",
  "Pouches",
  "Pouches|Accessory Holsters",
  "Pouches|Gun & Magazine Combo Holsters",
  "Pouches|Gun Holsters",
  "Pouches|Holster Accessories",
  "Pouches|Magazine Holsters",
  "Pouches|Muzzleloader Ramrods",
  "Powder Measures",
  "Powder Measures Dispensers & Scales",
  "Predator Calls",
  "Predator Decoys",
  "Press Parts & Accessories",
  "Press Parts & Accessories|Brass Catchers",
  "Press Parts & Accessories|Dies",
  "Presses|Case Prep Tools",
  "Primer Accessories & Fuses",
  "Progressive Presses",
  "Pull Through Bore Cleaners",
  "Punches",
  "Purses",
  "Purses|Bags & Packs",
  "Purses|Cases Safes & Storage",
  "Purses|Personal Defense & Security",
  "Quivers Belts & Carriers",
  "Rain Gear",
  "Range Accessories",
  "Range Bags",
  "Range Bags|Handgun Cases",
  "Range Bags|Pouches",
  "Range Bags|Shooting Rests",
  "Range Gear",
  "Range Gear|Gun Cleaning Accessories",
  "Rangefinders",
  "Rangefinders|Pouches",
  "Rangefinding Binoculars",
  "Rangefinding Binoculars|Rangefinding Binoculars",
  "Reactive Targets",
  "Recoil Pads",
  "Red Dot Sight Mounts & Adapters",
  "Red Dot Sight Mounts & Adapters|Picatinny-Style Universal Mounts",
  "Red Dot Sight Mounts & Adapters|Scope Bases & Mounts",
  "Red Dot Sights",
  "Reflex",
  "Reflex|Magnifier",
  "Reflex|Tube",
  "Releases & Accessories",
  "Reloading",
  "Reloading Kits",
  "Reloading Kits|Dies",
  "Reloading|Bullet Casting",
  "Reloading|Bullet Pullers",
  "Reloading|Calipers & Micrometers",
  "Reloading|Case Prep Tools",
  "Reloading|Die Parts Shell Holders & Accessories",
  "Reloading|Dies",
  "Reloading|Muzzleloader Bullets & Sabots",
  "Reloading|Muzzleloader Bullets & Sabots|Muzzleloader Bullets & Sabots",
  "Reloading|Pistol Brass",
  "Reloading|Pistol Bullets",
  "Reloading|Pistol Dies",
  "Reloading|Pistol Powder",
  "Reloading|Pistol Primers",
  "Reloading|Powder Measures Dispensers & Scales",
  "Reloading|Press Parts & Accessories",
  "Reloading|Presses|Case Prep Tools",
  "Reloading|Primer Accessories & Fuses",
  "Reloading|Reloading",
  "Reloading|Reloading Kits",
  "Reloading|Reloading|Rifle Bullets",
  "Reloading|Replacement Parts",
  "Reloading|Rifle Brass",
  "Reloading|Rifle Bullets",
  "Reloading|Rifle Dies",
  "Reloading|Rifle Powder",
  "Reloading|Rifle Primers",
  "Reloading|Shell Holders & Plates",
  "Reloading|Shotshell Primers|Percussion Caps & Primers",
  "Reloading|Single Stage Presses",
  "Reloading|Tumblers & Media",
  "Rifle Ammunition",
  "Rifle Brass",
  "Rifle Bullets",
  "Rifle Bullets|Muzzleloader Bullets & Sabots",
  "Rifle Cases",
  "Rifle Cases|Pouches",
  "Rifle Cases|Shotgun Cases",
  "Rifle Dies",
  "Rifle Lights",
  "Rifle Lights|Flashlights & Accessories",
  "Rifle Lights|Rifle Lights",
  "Rifle Lights|Grips",
  "Rifle Magazines",
  "Rifle Magazines|Magazine Speedloaders|Speedloaders & Accessories",
  "Rifle Magazines|Shotgun Magazines",
  "Rifle Parts",
  "Rifle Powder",
  "Rifle Primers",
  "Rifle Scopes",
  "Rifle Sights",
  "Rifle Storage",
  "Rifles",
  "Rifles|CA Compliant",
  "Rifles|CSSI Exclusive Shop",
  "Rifles|CSSI Exclusive Shop|Firearms",
  "Rifles|Chassis & Stocks",
  "Rifles|Firearms",
  "Rifles|Firearms|Firearms",
  "Rifles|Gun Parts|Uppers",
  "Rifles|Shotguns",
  "Rifles|Uppers",
  "Rifles|Used Guns",
  "Rifles|Used Guns|CA Compliant",
  "Rimfire Ammunition",
  "Rimfire Scopes",
  "Safe Accessories",
  "Safety Glasses",
  "Safety Glasses|Ear & Eye Combo Kits",
  "Safety Glasses|Shooting Glasses",
  "Sausage Stuffers",
  "Scent Attractants",
  "Scent Control Kits",
  "Scope Accessories",
  "Scope Bases & Mounts",
  "Scope Bases & Mounts|Barrels",
  "Scope Bases & Mounts|Chassis & Stocks",
  "Scope Bases & Mounts|Scope Rings",
  "Scope Bases & Mounts|Sling Accessories",
  "Scope Covers & Sunshades",
  "Scope Rings",
  "Scope/Sight Mounting",
  "Screwdrivers & Torque Wrenches",
  "Screwdrivers & Torque Wrenches|Gun Cleaning Kits",
  "Self Defense Accessories",
  "Self Defense Accessories|Flashlights & Accessories",
  "Sharpeners & Maintenance",
  "Sharpeners & Maintenance|Knives & Edged Tools",
  "Shell Holders",
  "Shell Holders & Plates",
  "Shell Holders & Plates|Replacement Parts",
  "Shell Holders|Brass Catchers",
  "Shell Holders|Pouches",
  "Shell Holders|Range Bags|Brass Catchers",
  "Shirts",
  "Shirts|Clothing & Footwear",
  "Shooting",
  "Shooting Glasses",
  "Shooting Patches & Wads",
  "Shooting Rests",
  "Shooting Rests|Bipods",
  "Shooting Rests|Shooting Sticks",
  "Shooting Sticks",
  "Shooting Vests",
  "Shooting Vests|Plate Carriers & Chest Rigs",
  "Shooting|Accessory Holsters",
  "Shooting|Adapters & Rails",
  "Shooting|Bipods",
  "Shooting|Brass Catchers",
  "Shooting|Chronographs & Shot Timers",
  "Shooting|Clay Target Throwers",
  "Shooting|Cleaning Brushes Mops and Swabs",
  "Shooting|Ear & Eye Combo Kits",
  "Shooting|Ear Muffs",
  "Shooting|Ear Plugs",
  "Shooting|Gun & Magazine Combo Holsters",
  "Shooting|Gun Cleaning Accessories",
  "Shooting|Gun Cleaning Jags Patch Holders & Patches",
  "Shooting|Gun Cleaning Kits",
  "Shooting|Gun Cleaning Rods",
  "Shooting|Gun Oils & Gun Cleaning Solvents",
  "Shooting|Magazine Speedloaders",
  "Shooting|Pouches",
  "Shooting|Pouches|Magazine Holsters",
  "Shooting|Rifle Cases|Shotgun Cases",
  "Shooting|Shooting Glasses",
  "Shooting|Shooting Rests",
  "Shooting|Sling Accessories",
  "Shooting|Slings",
  "Shooting|Speedloaders & Accessories",
  "Shooting|Steel Targets",
  "Shooting|Swivels",
  "Shooting|Target Stands & Accessories",
  "Short Barreled Rifles",
  "Short Barreled Rifles|Rifles",
  "Short Sleeve Shirts",
  "Short Sleeve Shirts|Clothing & Footwear",
  "Short Sleeve Shirts|Short Sleeve Shirts",
  "Shorts",
  "Shorts|Clothing & Footwear",
  "Shotgun Ammunition",
  "Shotgun Ammunition|Dummy Rounds|Snap Caps & Dummy Rounds|Snap Caps & Dummy Rounds",
  "Shotgun Cases",
  "Shotgun Lights",
  "Shotgun Magazines",
  "Shotgun Scopes",
  "Shotgun Sights",
  "Shotguns",
  "Shotguns|CA Compliant",
  "Shotguns|CA Compliant|MA Compliant",
  "Shotguns|Firearms",
  "Shotguns|Used Guns",
  "Shotshell Powder",
  "Shotshell Primers",
  "Shotshell Primers|Percussion Caps & Primers",
  "Shotshell Storage",
  "Sights & Scopes",
  "Sights & Scopes|Archery Scopes",
  "Single Stage Presses",
  "Single Stage Presses|Dies",
  "Slate & Glass Calls",
  "Sleeping Bags",
  "Sleeping Pads",
  "Slides",
  "Slides|Triggers",
  "Sling Accessories",
  "Sling Accessories|Adapters & Rails",
  "Slings",
  "Slings & Swivels",
  "Slings & Swivels|Adapters & Rails",
  "Slingshots and Accessories",
  "Slingshots and Accessories|Airgun Accessories",
  "Snap Caps & Dummy Rounds",
  "Snap Caps & Dummy Rounds|Snap Caps & Dummy Rounds",
  "Socks",
  "Socks|Socks",
  "Socks|Socks|Clothing & Footwear",
  "Software",
  "Speedloaders & Accessories",
  "Speedloaders & Accessories|Accessory Holsters",
  "Speedloaders & Accessories|Holster Accessories",
  "Speedloaders & Accessories|Pouches|Accessory Holsters",
  "Spotting Scope Tripods & Mounting",
  "Spotting Scope Tripods & Mounting|Shooting Rests",
  "Spotting Scope Tripods & Mounting|Tripods",
  "Spotting Scopes",
  "Stabilizers & Dampers",
  "Steel Targets",
  "Stock/Chassis Bedding",
  "Storage",
  "Storage & Organization Accessories",
  "Storage|Ammo Boxes",
  "Stoves & Grills",
  "Stun Guns",
  "Sunglasses",
  "Sunglasses|Shooting Glasses",
  "Sunglasses|Shooting Rests|Shooting Glasses",
  "Sunglasses|Shooting|Shooting Glasses",
  "Sunglasses|Sunglasses|Shooting Glasses",
  "Suppressor Cleaners",
  "Suppressor Cleaners|Gun Oils & Gun Cleaning Solvents",
  "Suppressor Height Sights",
  "Suppressors",
  "Suppressors Accessories",
  "Suppressors Accessories|Gun Parts|Muzzle Devices",
  "Suppressors Accessories|Knives",
  "Suppressors Accessories|Muzzle Devices",
  "Suppressors Accessories|Packs & Bags",
  "Suppressors Accessories|Suppressor Cleaners",
  "Suppressors and Parts",
  "Suppressors|Gun Parts",
  "Suppressors|Handguns",
  "Suppressors|Muzzle Devices",
  "Suppressors|Suppressors",
  "Suppressors|Used Guns",
  "Swivels",
  "Swivels|Sling Accessories",
  "TASER Accessories",
  "TASER Accessories|Accessory Holsters",
  "TASER Devices",
  "Tables",
  "Tabs Slings Guards & Gloves",
  "Target Stands & Accessories",
  "Targets",
  "Targets|Paper Targets",
  "Thermal Accessories",
  "Thermal Accessories|Scope Rings",
  "Thermal Binoculars",
  "Thermal Imaging",
  "Thermal Imaging Cameras",
  "Thermal Monoculars",
  "Thermal Rifle Scopes",
  "Thermal Rifle Scopes|Thermal Imaging Cameras",
  "Tools",
  "Tools|Cleaning Brushes Mops and Swabs",
  "Tools|Die Parts Shell Holders & Accessories",
  "Tools|Gun Bore Guides",
  "Tools|Gun Cleaning Tools",
  "Tower Stands",
  "Traditional Bows",
  "Trail Camera Accessories",
  "Trail Camera Accessories|Health & Safety",
  "Treestand Accessories",
  "Treestand Accessories|Accessories",
  "Treestand Accessories|Archery Accessories",
  "Treestand Accessories|Shooting Rests",
  "Tree Saddles",
  "Tree Saddles|Hunting",
  "Treestand Safety Harnesses",
  "Trigger Pull Gauges",
  "Trigger Pull Gauges|Powder Measures Dispensers & Scales",
  "Triggers",
  "Tripods",
  "Tube",
  "Tube|Shotgun Scopes",
  "Tumblers & Media",
  "Turkey Calls",
  "Turkey Decoys",
  "Turkey Decoys|Hunting",
  "Turkey Decoys|Locator Calls",
  "Turkey Vests",
  "Turkey Vests|Clothing & Footwear",
  "Turkey Vests|Shooting Vests",
  "Turret Presses",
  "Ultrasonic Cleaners & Dryers",
  "Ultrasonic Gun Cleaners",
  "Upland Calls",
  "Upland Vests",
  "Upland Vests|Cases Safes & Storage|Shooting Vests",
  "Upland Vests|Hunting Packs",
  "Uppers",
  "Used Guns",
  "Utensils",
  "Vacuum Sealers",
  "Vacuum Sealers|Hunting",
  "Vests",
  "Vests|Collars Leashes & Harnesses",
  "Vests|Hunting Safety",
  "Vests|Rain Gear",
  "Vests|Shooting Vests",
  "Vests|Vests",
  "Vices & Cradles",
  "Waders & Wading Boots",
  "Waders & Wading Boots|Clothing & Footwear",
  "Waders & Wading Boots|Waders & Wading Boots",
  "Waist Packs",
  "Waist Packs|Packs & Bags",
  "Water Bottles",
  "Water Bottles|Hydration Packs",
  "Water Treatment",
  "Waterfowl Blinds",
  "Waterfowl Blinds|Hunting",
  "Weapon Lights",
  "Windmeters & Flags",
  "Youth Bows"
];

// Function to determine site category from Chattanooga category
function mapCategory(chattanoogaCategory) {
  const cat = chattanoogaCategory.toLowerCase();

  // Ammunition
  if (cat.includes('ammunition') || cat.includes('handgun ammunition') ||
      cat.includes('rifle ammunition') || cat.includes('shotgun ammunition') ||
      cat.includes('rimfire ammunition')) {
    return 'ammunition';
  }

  // Gun Parts
  if (cat.includes('gun parts') || cat.includes('barrels') || cat.includes('triggers') ||
      cat.includes('grips') || cat.includes('handguards') || cat.includes('chassis & stocks') ||
      cat.includes('bolt carriers') || cat.includes('lowers') || cat.includes('uppers') ||
      cat.includes('muzzle devices') || cat.includes('chokes') || cat.includes('recoil pads') ||
      cat.includes('caliber conversions') || cat.includes('parts/parts kits') ||
      cat.includes('parts') || cat.includes('rifle parts') || cat.includes('gun parts & tools') ||
      cat.includes('replacement parts') || cat.includes('gun parts|tools')) {
    return 'gun-parts';
  }

  // Magazines
  if (cat.includes('magazines') || cat.includes('handgun magazines') ||
      cat.includes('rifle magazines') || cat.includes('shotgun magazines') ||
      cat.includes('magazine accessories') || cat.includes('magazine releases') ||
      cat.includes('magazine extensions') || cat.includes('magazine catches') ||
      cat.includes('magazine speedloaders') || cat.includes('magazine storage') ||
      cat.includes('magazine tubes') || cat.includes('magazine holsters') ||
      cat.includes('magazine pouches')) {
    return 'magazines';
  }

  // Optics
  if (cat.includes('optics') || cat.includes('scopes') || cat.includes('rifle scopes') ||
      cat.includes('handgun scopes') || cat.includes('shotgun scopes') || cat.includes('rimfire scopes') ||
      cat.includes('binoculars') || cat.includes('monoculars') || cat.includes('spotting scopes') ||
      cat.includes('rangefinders') || cat.includes('rangefinding binoculars') ||
      cat.includes('night vision') || cat.includes('thermal') || cat.includes('red dot sights') ||
      cat.includes('reflex') || cat.includes('magnifier') || cat.includes('tube') ||
      cat.includes('sights & scopes') || cat.includes('archery scopes') ||
      cat.includes('scope bases & mounts') || cat.includes('scope rings') ||
      cat.includes('scope covers & sunshades') || cat.includes('scope accessories') ||
      cat.includes('bases & mounts by gun make & model') || cat.includes('laser sights') ||
      cat.includes('night sights') || cat.includes('rifle lights') || cat.includes('handgun lights') ||
      cat.includes('weapon lights') || cat.includes('rifle sights') || cat.includes('handgun sights') ||
      cat.includes('shotgun sights') || cat.includes('fiber optic sights') ||
      cat.includes('red dot sight mounts & adapters') || cat.includes('thermal accessories') ||
      cat.includes('thermal imaging cameras') || cat.includes('thermal monoculars') ||
      cat.includes('thermal rifle scopes') || cat.includes('thermal binoculars') ||
      cat.includes('night vision rifle scopes') || cat.includes('night vision binoculars') ||
      cat.includes('night vision goggles') || cat.includes('night vision monoculars') ||
      cat.includes('night vision accessories')) {
    return 'optics';
  }

  // Reloading
  if (cat.includes('reloading') || cat.includes('dies') || cat.includes('presses') ||
      cat.includes('bullet casting') || cat.includes('brass') || cat.includes('primers') ||
      cat.includes('powder') || cat.includes('calipers & micrometers') ||
      cat.includes('case prep tools') || cat.includes('die parts shell holders & accessories') ||
      cat.includes('powder measures dispensers & scales') || cat.includes('press parts & accessories') ||
      cat.includes('primer accessories & fuses') || cat.includes('reloading kits') ||
      cat.includes('replacement parts') || cat.includes('shell holders & plates') ||
      cat.includes('shotshell primers') || cat.includes('tumblers & media') ||
      cat.includes('single stage presses') || cat.includes('progressive presses') ||
      cat.includes('turret presses') || cat.includes('bullet pullers') ||
      cat.includes('percussion caps & primers') || cat.includes('percussion cap')) {
    return 'reloading';
  }

  // Outdoors
  if (cat.includes('hunting') || cat.includes('outdoors') || cat.includes('camping') ||
      cat.includes('archery') || cat.includes('bows') || cat.includes('arrows') ||
      cat.includes('crossbows') || cat.includes('treestands') || cat.includes('blinds') ||
      cat.includes('decoys') || cat.includes('calls') || cat.includes('trail cameras') ||
      cat.includes('game processing') || cat.includes('meat grinders') || cat.includes('meat mixers') ||
      cat.includes('meat saws') || cat.includes('meat slicers') || cat.includes('sausage stuffers') ||
      cat.includes('vacuum sealers') || cat.includes('feeders') || cat.includes('scent') ||
      cat.includes('dog training') || cat.includes('dog blinds') || cat.includes('waterfowl blinds') ||
      cat.includes('ground blinds') || cat.includes('climbing sticks') || cat.includes('ladder treestands') ||
      cat.includes('hang on treestands') || cat.includes('tower stands') || cat.includes('tree saddles') ||
      cat.includes('treestand accessories') || cat.includes('treestand safety harnesses') ||
      cat.includes('big game decoys') || cat.includes('duck decoys') || cat.includes('goose decoys') ||
      cat.includes('turkey decoys') || cat.includes('predator decoys') || cat.includes('dove decoys') ||
      cat.includes('locator calls') || cat.includes('mouth calls') || cat.includes('slate & glass calls') ||
      cat.includes('electronic calls') || cat.includes('electronic game calls') || cat.includes('predator calls') ||
      cat.includes('deer calls') || cat.includes('elk calls') || cat.includes('goose calls') ||
      cat.includes('duck calls') || cat.includes('turkey calls') || cat.includes('upland calls') ||
      cat.includes('box calls') || cat.includes('decoy accessories') || cat.includes('decoy bags') ||
      cat.includes('quivers belts & carriers') || cat.includes('releases & accessories') ||
      cat.includes('tabs slings guards & gloves') || cat.includes('stabilizers & dampers') ||
      cat.includes('broadheads field & specialty points') || cat.includes('arrow building & repair') ||
      cat.includes('arrow components') || cat.includes('arrow rests') || cat.includes('arrow tubes & cases') ||
      cat.includes('arrows') || cat.includes('youth bows') || cat.includes('traditional bows') ||
      cat.includes('compound bows') || cat.includes('crossbow accessories') || cat.includes('crossbow targets') ||
      cat.includes('archery accessories') || cat.includes('mathews bridge-lock sights & accessories') ||
      cat.includes('peep sights') || cat.includes('3d targets') || cat.includes('block & foam targets') ||
      cat.includes('bag targets') || cat.includes('reactive targets') || cat.includes('steel targets') ||
      cat.includes('paper targets') || cat.includes('clay target throwers') || cat.includes('target stands & accessories') ||
      cat.includes('trail camera accessories') || cat.includes('cellular trail cameras') ||
      cat.includes('non cellular trail cameras') || cat.includes('food plots') || cat.includes('minerals & attractants') ||
      cat.includes('food dehydrators') || cat.includes('stoves & grills') || cat.includes('firepits & heating') ||
      cat.includes('cookware') || cat.includes('utensils') || cat.includes('water bottles') ||
      cat.includes('hydration packs') || cat.includes('water treatment') || cat.includes('portable showers') ||
      cat.includes('sleeping bags') || cat.includes('sleeping pads') || cat.includes('beds & pads') ||
      cat.includes('beds') || cat.includes('hammocks') || cat.includes('chairs') || cat.includes('tables') ||
      cat.includes('blind chairs') || cat.includes('backpacking') || cat.includes('backpacks') ||
      cat.includes('packs & bags') || cat.includes('dry bags') || cat.includes('bags & duffels') ||
      cat.includes('waist packs') || cat.includes('hunting packs') || cat.includes('turkey vests') ||
      cat.includes('upland vests') || cat.includes('hunting vests') || cat.includes('hunting pants') ||
      cat.includes('rain gear') || cat.includes('jackets coats & parkas') || cat.includes('hoodies & sweatshirts') ||
      cat.includes('long sleeve shirts') || cat.includes('short sleeve shirts') || cat.includes('shirts') ||
      cat.includes('pants') || cat.includes('shorts') || cat.includes('socks') || cat.includes('boots & shoes') ||
      cat.includes('waders & wading boots') || cat.includes('caps hats & beanies') || cat.includes('hats') ||
      cat.includes('facemasks balaclavas & neck gaiters') || cat.includes('gloves') || cat.includes('belts') ||
      cat.includes('holster & duty belts') || cat.includes('vests') || cat.includes('shooting vests') ||
      cat.includes('plate carriers') || cat.includes('plate carriers & chest rigs') || cat.includes('pfd') ||
      cat.includes('insect repellants') || cat.includes('hygiene products') || cat.includes('laundry detergent') ||
      cat.includes('first aid') || cat.includes('first aid kits') || cat.includes('health & safety') ||
      cat.includes('emergency & survival') || cat.includes('compasses') || cat.includes('lanterns') ||
      cat.includes('headlamps') || cat.includes('flashlights') || cat.includes('flashlights & accessories') ||
      cat.includes('batteries') || cat.includes('food') || cat.includes('windmeters & flags') ||
      cat.includes('dog blinds') || cat.includes('dog training') || cat.includes('collars & leashes') ||
      cat.includes('collars leashes & harnesses') || cat.includes('electronic collars') ||
      cat.includes('training') || cat.includes('toys') || cat.includes('bear safety gear') ||
      cat.includes('pepper spray') || cat.includes('pepper gun accessories') || cat.includes('pepper guns') ||
      cat.includes('self defense accessories') || cat.includes('personal defense & security') ||
      cat.includes('handcuffs & restraints') || cat.includes('stun guns') || cat.includes('taser accessories') ||
      cat.includes('taser devices') || cat.includes('software') || cat.includes('manuals') ||
      cat.includes('shooting|paper targets') || cat.includes('shooting|pull through bore cleaners')) {
    return 'outdoors';
  }

  // Gear (catch-all for accessories, holsters, cases, cleaning, etc.)
  return 'gear';
}

// Create the mapping
const categoryMapping = {};
CHATTANOOGA_CATEGORIES.forEach(cat => {
  categoryMapping[cat] = mapCategory(cat);
});

// Write to file
const output = {
  siteCategories: SITE_CATEGORIES,
  chattanoogaToSiteMapping: categoryMapping,
  mappingSummary: SITE_CATEGORIES.reduce((acc, siteCat) => {
    acc[siteCat] = Object.values(categoryMapping).filter(mapped => mapped === siteCat).length;
    return acc;
  }, {})
};

fs.writeFileSync('category_mapping.json', JSON.stringify(output, null, 2));
console.log('Category mapping created successfully!');
console.log('Mapping summary:', output.mappingSummary);